### ISSUE TITLE
Wrong class meeting address

### ISSUE THREAD

**Issue by jfushada** [joannakl/cs480_s18#10]
On the home page, it states that the class meetings are at CIWW, Room C10, while it should be at 60 5th Avenue, Room C10.

Browser: Chrome Version 63.0.3239.132

**Comment by PhrydRhys** [comment]
I also see this issue with Version 62.0.3202.75 of Google Chrome.
I believe the source of this misinformation is located in the [_config.yml](https://github.com/joannakl/cs480_s18/blob/gh-pages/_config.yml#L23) file.

**Comment by eschadt** [comment]
I would like to claim this issue!

**Comment by joannakl** [comment]
@eschadt  go ahead and fix this issue

**Comment by eschadt** [comment]
@jfushada Does this fix satisfy the problem you described? is no further work required?

**Comment by jfushada** [comment]
@eschadt yes! I commented that it was good in the pull request thread, and Professor Klukowska already merged and closed the issue.
