### ISSUE TITLE
Inconsistent underlining on syllabus page

### ISSUE THREAD

**Issue by dorasun** [joannakl/cs480_s18#104]
For most of the topics on the syllabus page (https://joannakl.github.io/cs480_s18/syllabus.html), there is an underline under the topic: 
<img width="483" alt="screen shot 2018-04-03 at 5 28 02 pm" src="https://user-images.githubusercontent.com/10905385/38276895-8966e1f8-3764-11e8-81fb-52523dab1890.png">
<img width="444" alt="screen shot 2018-04-03 at 5 28 23 pm" src="https://user-images.githubusercontent.com/10905385/38276896-8b578e5e-3764-11e8-80a7-f1e8bbeaeacc.png">

But for Prerequisites, there is a line above the word, and Open Source News sites has no underline at all. This is seen on Chrome 65.0.3325.181, MacOS 10.12.5:
<img width="1108" alt="screen shot 2018-04-03 at 5 28 31 pm" src="https://user-images.githubusercontent.com/10905385/38277006-e304430e-3764-11e8-8ed4-55a714432571.png">

The fix should be in syllabus.markdown, approx lines 21 and 31

**Comment by ashley-hu** [comment]
I see the same thing on Safari Version 11.0.3 (11604.5.6.1.1) and MacOS Version 10.11.6. 

However, I believe this is deliberate rather than an actual issue.

**Comment by joannakl** [comment]
This was not deliberate. I think it was one of the bugs introduced early on and nobody picked up on it.

**Comment by jfushada** [comment]
I'd like to claim the issue, please!

**Comment by joannakl** [comment]
@jfushada  it is yours
