### ISSUE TITLE
tryGit link misformatted

### ISSUE THREAD

**Issue by felixplajer** [joannakl/cs480_s18#11]
On the daily page under class 5, the link to tryGit is formatted incorrectly.

Browser: Chrome 63.0.3239.132

**Comment by PhrydRhys** [comment]
The mis-formatting is also evident in Version 62.0.3202.75 of Google Chrome.

**Comment by eschadt** [comment]
Indeed it is! 
the  html for this link is as follows:

<p>if you are not comfortable with using git from the terminal, go through the [t]ryGit(https://try.github.io/levels/1/challenges/1) tutorial</p>

 the <a> tag needs to be used inside the <p> tags to turn trygit into a hyperlink.

**Comment by ghost** [comment]
Hi, I'd like to claim this issue. :)

**Comment by wentaozou1** [comment]
I think the tryGit should be inside [] so that it will be a clickable link.

**Comment by joannakl** [comment]
@juliandorville  go ahead and fix this issue
