### ISSUE TITLE
Tom Callaway's Company

### ISSUE THREAD

**Issue by PhrydRhys** [joannakl/cs480_s18#12]
Under "Class 3", it says that Tom Callaway is from "Bluefish". However, I believe the company that he works for is "RedHat".

Browser: Google Chrome, Version 62.0.3202.75

**Comment by ashley-hu** [comment]
Yes, I see the same issue. I am using Google Chrome, Version: 63.0.3239.132

**Comment by ghost** [comment]
I was going to post this one—good find!

**Comment by dayo-adebanjo** [comment]
Issue can be found here: https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/03.markdown

**Comment by ashley-hu** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
@ashley-hu  go ahead and fix this issue
