### ISSUE TITLE
Incorrect Link to Daily from Syllabus

### ISSUE THREAD

**Issue by ckilcrease** [joannakl/cs480_s18#13]
The "Daily" link in the syllabus (at the bottom of the "topics covered" section: "For detailed schedule, see the Daily tab of this page.") just links back to the syllabus page, instead of the actual daily page.

I'm using Google Chrome version 63.0.3239.132

**Comment by suyasha0** [comment]
I found the same issue using Microsoft Edge.

**Comment by PhrydRhys** [comment]
I believe the issue is the similar to that of [Issue #4](https://github.com/joannakl/cs480_s18/issues/4)

**Comment by ckilcrease** [comment]
Hmm, it seems to be caused by a separate problem though, because in syllabus.markdown (if you view the raw file) the link to syllabus.html is provided, although it should link to daily.html

**Comment by PhrydRhys** [comment]
Yes, I believe you are correct; I misread which "Daily" link you were referring to, and agree the location you have provided as the cause of this problem

**Comment by felixplajer** [comment]
I'd like to work on this issue.

**Comment by joannakl** [comment]
@felixplajer  go ahead and fix this issue

**Comment by felixplajer** [comment]
PR submitted to fix this [here](https://github.com/joannakl/cs480_s18/pull/75).
