### ISSUE TITLE
Midterm Exam is listed as 200% of Final Grade

### ISSUE THREAD

**Issue by ghost** [joannakl/cs480_s18#15]
On the Grading section of the website

Using Chrome 64.0.3282.140

**Comment by ryanchau** [comment]
The issue is found on https://joannakl.github.io/cs480_s18/syllabus.html under the Grading section. 

Should be listed as 20%.

**Comment by dayo-adebanjo** [comment]
I see the issue on my browser version as well (Chrome 63.0.3239.132)

**Comment by AlvaroLuken** [comment]
I can also confirm this issue and it can be found inside the repo at: https://github.com/joannakl/cs480_s18/blob/gh-pages/syllabus.markdown

**Comment by danagilliann** [comment]
Claimed

**Comment by joannakl** [comment]
@danagilliann : go ahead and fix the issue
