### ISSUE TITLE
2/8 wrong day of the week

### ISSUE THREAD

**Issue by oekonomi** [joannakl/cs480_s18#18]
In the daily section, 2/8 is listed as a Tuesday when it's a Thursday

**Comment by GS-14** [comment]
Also an issue on Chrome Version 64.0.3282.140.  
Minor typo, error in the column_date div in daily.html.

**Comment by JimenezJC** [comment]
The typo seems to be located here https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/06.markdown

**Comment by kellyhogan** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
@kellyhogan go ahead and fix this issue
