### ISSUE TITLE
Questionnaire misspelling

### ISSUE THREAD

**Issue by danagilliann** [joannakl/cs480_s18#19]
The word "questionnaire" under "Daily" is spelled as "questionnnaire"

Version 63.0.3239.132

**Comment by extra-mayo** [comment]
Can confirm, I'm seeing the same error using Google Chrome 63.0.3239.132

**Comment by ashley-hu** [comment]
Can also confirm. I am using Google Chrome (64.0.3282.140). The cause of the issue can be found here https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/01.markdown

**Comment by melissaelopez** [comment]
I can work on this issue!

**Comment by ashley-hu** [comment]
I would like to work on this issue.

**Comment by joannakl** [comment]
@melissaelopez  go ahead and work on this issue
