### ISSUE TITLE
"Practical Open Source Software Exploration" book image not present

### ISSUE THREAD

**Issue by Amethystix** [joannakl/cs480_s18#22]
There appears to have been an image in that space, as in the html there is an image with a src that doesn't lead anywhere, so I assume the image needs to be linked properly. Using Google Chrome Ver. 64.0.3282.140

**Comment by extra-mayo** [comment]
Yup, the image tag shows that src is blank. 
`<img src="" name="Book" border="0px" width="120px">`

**Comment by ashley-hu** [comment]
I found the cause for the issue here:  https://github.com/joannakl/cs480_s18/blob/b9d1886fb74bcf31973bc547a788fd4de0d628e2/_config.yml#L70  The image link is empty. I believe the image link needs to be provided here in order for the image to appear.

**Comment by GS-14** [comment]
I'd like to claim this.

**Comment by joannakl** [comment]
@GS-14 which image are you proposing to include there? if there is one that is appropriate, go ahead and fix that issue

**Comment by GS-14** [comment]
@joannakl The best one I found so far is:  
https://quaid.fedorapeople.org/TOS/Practical_Open_Source_Software_Exploration/html-single/Common_Content/images/title_logo.svg  
Is that fine?
