### ISSUE TITLE
Unnecessary ellipsis in Topics Covered 

### ISSUE THREAD

**Issue by rosaswaby** [joannakl/cs480_s18#26]
When you go to the Topics Covered section of Daily, there is an empty bullet point with ellipsis. 
Chrome Version: 64.0.3282.140

![](https://user-images.githubusercontent.com/9499838/35995365-1435f1f6-0ce1-11e8-8b63-f382ca504286.png)

**Comment by rosaswaby** [comment]
<img width="330" alt="screen shot 2018-02-08 at 3 01 36 pm" src="https://user-images.githubusercontent.com/9499838/35995365-1435f1f6-0ce1-11e8-8b63-f382ca504286.png">

**Comment by dorasun** [comment]
I'm also bothered by the inconsistent use of commas. A bulleted list like this shouldn't need commas at all.

**Comment by danagilliann** [comment]
Can confirm with Version 63.0.3239.132
Can be fixed here: https://github.com/joannakl/cs480_s18/blob/b9d1886fb74bcf31973bc547a788fd4de0d628e2/syllabus.markdown

**Comment by JFernandes1** [comment]
I think the ellipses might be intentional to show that there are more unlisted examples?

**Comment by joannakl** [comment]
Agreed - this is not really an issue.
