### ISSUE TITLE
Academic Email Etiquette and Academic Integrity Policy are switched 

### ISSUE THREAD

**Issue by swang96** [joannakl/cs480_s18#27]
https://joannakl.github.io/cs480_s18/syllabus.html

The information for academic email etiquette and academic integrity policy are switched with each other under the course syllabus.

**Comment by eschadt** [comment]
confirmed! The email etiquette and academic integrity policy are indeed switched!

**Comment by ghost** [comment]
+1, using Firefox 58.0.2.

I think the two texts have been switched in [syllabus.markdown](https://github.com/joannakl/cs480_s18/blob/gh-pages/syllabus.markdown).

**Comment by ckilcrease** [comment]
I would like to work on this issue!

**Comment by joannakl** [comment]
@ckilcrease  go ahead and fix this issue
