### ISSUE TITLE
The descriptions underneath "Videos" are formatted incorrectly

### ISSUE THREAD

**Issue by extra-mayo** [joannakl/cs480_s18#28]
Google Chrome | 63.0.3239.132 (Official Build) (64-bit) (cohort: Stable)

![image](https://user-images.githubusercontent.com/15808322/35995915-dc04c828-0ce2-11e8-9071-ed819d5312d2.png)

**Comment by oekonomi** [comment]
I'm seeing this issue too.  It looks like a couple of line breaks are missing

**Comment by Matthew-Herman** [comment]
This can be fixed by navigating in the repository to https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/01.markdown and adding proper formatting with markdown.

**Comment by JimenezJC** [comment]
Also experiencing this bug on Chromium Version 63.0.3239.132 (Developer Build) (64-bit). Should be an easy fix.

**Comment by extra-mayo** [comment]
I'd like to claim this issue!

**Comment by joannakl** [comment]
@extra-mayo  you cannot be fixing your own issue - this was a rule

**Comment by extra-mayo** [comment]
@joannakl  woops, sorry about that!

**Comment by riosr2** [comment]
I'd like to claim this issue

**Comment by joannakl** [comment]
@riosr2  go for it
