### ISSUE TITLE
Typo for class meeting times

### ISSUE THREAD

**Issue by melissaelopez** [joannakl/cs480_s18#30]
The website lists “Tuesdays and Thursdays 11:00PM - 12:15AM.” Misuse of PM/AM.

**Comment by eschadt** [comment]
confirmed! PM/AM are misused for the class meeting times!

**Comment by rosaswaby** [comment]
can confirm this as well! the issue might be found in the _config.yml file for the class website

**Comment by Matthew-Herman** [comment]
Confirmed. The course_time variable needs to be changed in https://github.com/joannakl/cs480_s18/blob/gh-pages/_config.yml as @rosaswaby mentioned.

Also I want to add that there is a style discrepancy between "AM - PM" under class meetings and "am - pm" under office hours. Maybe someone can open a new issue on that.

**Comment by suyasha0** [comment]
Can I work on this issue?

**Comment by joannakl** [comment]
@suyasha0 go ahead and work on this issue
