### ISSUE TITLE
Data Structures roster included in repo

### ISSUE THREAD

**Issue by ashleytqy** [joannakl/cs480_s18#31]
Don't think this https://github.com/joannakl/cs480_s18/blob/gh-pages/NYU_RS_PHOTO-1.pdf is supposed to be in the repo. It says "DO NOT DISTRIBUTE OR POST".

**Comment by joannakl** [comment]
Like you said, this file was not supposed to be there. This is something I needed to deal with right away. Good catch!

**Comment by joannakl** [comment]
File removed by JK.
