### ISSUE TITLE
Typo under "Licensing"

### ISSUE THREAD

**Issue by ghost** [joannakl/cs480_s18#33]
The phrase should read "how to _license_ your own work." (No 's')

![screen shot 2018-02-09 at 21 36 36](https://user-images.githubusercontent.com/22824699/36067065-cc88adfe-0e83-11e8-8b34-e64ca7499789.png)

Using Firefox Quantum 52.0.2 on MacOS 10.13.3.

**Comment by adnanislam** [comment]
This issue is also confirmed to exist on Chrome Version 64.0.3282.140 (Official Build) (64-bit). This issue can be resolved at https://github.com/joannakl/cs480_s18/blob/gh-pages/syllabus.markdown.

**Comment by S1MB10T3** [comment]
I claim this issue!

**Comment by kellyhogan** [comment]
I would like to work on this issue.

**Comment by joannakl** [comment]
@Rantahu  go ahead and work on this issue
