### ISSUE TITLE
Unclosed parenthesis on Text Books page

### ISSUE THREAD

**Issue by JimenezJC** [joannakl/cs480_s18#34]
There is an unclosed parenthesis following the information provided for the Practical Open Source Software Explorations textbook.

![screenshot_20180210-182234_2](https://user-images.githubusercontent.com/17581970/36067686-1c74ab4a-0e90-11e8-840a-ff3ab04073c2.png)

Chromium Version 64.0.3282.119 (Developer Build) (64-bit)

**Comment by adnanislam** [comment]
This issue is also confirmed to exist on Chrome Version 64.0.3282.140 (Official Build) (64-bit). The issue can be fixed at https://github.com/joannakl/cs480_s18/blob/gh-pages/_config.yml#L69.

**Comment by dmckenna24** [comment]
This issue is also apparent on Safari v. 11.0.3, and can be fixed [here](https://github.com/joannakl/cs480_s18/blob/gh-pages/_config.yml#L69) by adding the missing parenthesis.

**Comment by rosaswaby** [comment]
I would like to claim this issue!

**Comment by joannakl** [comment]
@rosaswaby  go ahead and work on this issue
