### ISSUE TITLE
'Cathedral' is mispelled as 'Catherdral'

### ISSUE THREAD

**Issue by AlvaroLuken** [joannakl/cs480_s18#35]
The issue is in the tab that starts with: "if you have not done so already, go to Piazza and vote for the date of the midterm exam" - I cannot give many other references as most parts of this tab are broken.

Also, the article is not hyperlinked anywhere in the page as I remember it was at one point - I hope someone brings this issue up separately. 

I am using Google Chrome, Version 63.0.3239.132 (Official Build) (64-bit).

<img width="982" alt="screen shot 2018-02-11 at 4 25 14 pm" src="https://user-images.githubusercontent.com/25407127/36078793-2c143958-0f49-11e8-93d6-81b2f4c98c14.png">

**Comment by dmckenna24** [comment]
I can confirm this issue, using Safari v. 11.0.3. And the misspelling can be found in on [line 16](https://github.com/joannakl/cs480_s18/edit/gh-pages/_includes/daily/04.markdown#L16)

**Comment by cr4zyafrican** [comment]
This is a confirmed issue as the Merriam Webster Dictionary spells is it as Cathedral. https://www.merriam-webster.com/dictionary/cathedral

Chrome  63.0.3239.132

**Comment by cr4zyafrican** [comment]
I claim this issue.

**Comment by dorasun** [comment]
Can I work on this issue?

**Comment by joannakl** [comment]
@cr4zyafrican  go ahead and fix the issue
