### ISSUE TITLE
Missing word "are" in blog post question 

### ISSUE THREAD

**Issue by dmckenna24** [joannakl/cs480_s18#36]
Under class 4's blog post, it says the following "quote them in your blog and try to explain what they supposed to mean" and the sentence should have the word "are" between they and supposed. 

Safari v. 11.0.3

**Comment by AlvaroLuken** [comment]
I can confirm this issue exists in the page. 
I am using Google Chrome, Version 63.0.3239.132 (Official Build) (64-bit).

Issue should be easily solved by simply adding "are" in 04.markdown file.

I notice your "# 4" links to some other area, just pointing that out to avoid any possible confusion.

Find image of tab and error below:

<img width="982" alt="screen shot 2018-02-11 at 4 25 14 pm" src="https://user-images.githubusercontent.com/25407127/36078709-3e7759dc-0f48-11e8-9150-18bc5bdb216c.png">

**Comment by mzguimaraes** [comment]
Confirming this issue as well (Chrome 63.0.3239.84 (Official Build) (64-bit))

The error appears to be on line 41, judging from daily/04.markdown's [blame page](https://github.com/joannakl/cs480_s18/blame/gh-pages/_includes/daily/04.markdown).

**Comment by dayo-adebanjo** [comment]
Claiming this issue!

**Comment by joannakl** [comment]
@dayo-adebanjo  you can work on this issue

**Comment by dmckenna24** [comment]
This is resolved!
