### ISSUE TITLE
Midterm and Final Dates not posted

### ISSUE THREAD

**Issue by cr4zyafrican** [joannakl/cs480_s18#38]
On the home page, the exam dates have not been posted and the course website should be updated with this information.

Chrome 63.0.3239.132

**Comment by mzguimaraes** [comment]
I believe this is intended behavior, as I don't think the midterm date has been announced yet.  Joanna may still be waiting on people to vote.

[Source](https://piazza.com/class/jccbxbx7axjji?cid=13)

Chrome 63.0.3239.84 (Official Build) (64-bit)

**Comment by felixplajer** [comment]
Now that the midterm date has been announced (March 8) we can add it.

**Comment by natalietotonchy** [comment]
I would like to claim this issue

**Comment by joannakl** [comment]
@natalietotonchy  go ahead with fixing this
