### ISSUE TITLE
Improper usage of semicolons

### ISSUE THREAD

**Issue by mzguimaraes** [joannakl/cs480_s18#39]
This passage from the Class #4 homework description:
> The Cathedral and The Bazaar essay has 19 "lessons"; pick two that you found most interesting, intriguing, telling, or that you simply liked; quote them in your blog and try to explain what they supposed to mean

Each usage of a semicolon here is incorrect, and sentence breaks would serve better. 

Unlike many programming languages, the English language does not require commands to be separated by semicolons.  Semicolons are hard to use correctly; it is therefore recommended to use them sparingly to avoid the wrath of those who care too much about grammar.

Observed on Google Chrome 63.0.3239.84 (Official Build) (64-bit)

**Comment by natalietotonchy** [comment]
Confirming that this issue exists using Safari version 11.0 (13604.1.38.1.6). The grammatical error can be fixed here: https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/04.markdown 

It should be noted however that perhaps the author chose to deliberately defy the constraints of grammatical rules.

**Comment by mzguimaraes** [comment]
I'd like to claim this issue.

**Comment by extra-mayo** [comment]
I'd like to claim this issue!

**Comment by joannakl** [comment]
@extra-mayo  you can work on this issue, but you may need to get some further feedback for what the  change should be
