### ISSUE TITLE
Navbar links doesn't link to correct pages

### ISSUE THREAD

**Issue by ashleytqy** [joannakl/cs480_s18#4]
Currently, the `Syllabus` tab links to the daily schedule, and the `Daily` tab links to the syllabus page.

<img width="799" alt="screen shot 2018-02-08 at 12 15 55 pm" src="https://user-images.githubusercontent.com/11889765/35987516-e0453576-0cc9-11e8-95ed-9df798379502.png">

**Comment by dorasun** [comment]
Problem found under _includes/header.html, lines 10 and 11 have the wrong labels for the wrong links, see https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/header.html#L10-L11

**Comment by cr4zyafrican** [comment]
Can confirm this issue with Chrome 63.0.3239.132

**Comment by gabegordon** [comment]
This issue also occurs for me. 
Using: Firefox 59.0b7

**Comment by Matthew-Herman** [comment]
I'd like to claim this issue.

**Comment by joannakl** [comment]
@Matthew-Herman : go ahead with the fix for this issue
