### ISSUE TITLE
Correct misspelt 

### ISSUE THREAD

**Issue by cr4zyafrican** [joannakl/cs480_s18#40]
The top of the website had a disclaimer: "This page currently has a lot of broken information - it is participating in class exercise. It should return to its corrent state shortly." It should be correct state.

Chrome 63.0.3239.132

**Comment by S1MB10T3** [comment]
lol corrent... I get the same error.
Chromium Version 64.0.3282.119

Issue can be found here at `cs480_s18/_includes/head.html`
```
    <b>This page currently has a lot of broken information - it is participating in class exercise. It should return to its 
    corrent state shortly. </b>
```

**Comment by riosr2** [comment]
I can also confirm this bug (Safari Version 9.1.1 (10601.6.17)). Should be an easy fix.

**Comment by riosr2** [comment]
I would like to claim this issue

**Comment by joannakl** [comment]
I am going to veto this one. This bug does not affect the final state o the website and the disclaimer will be removed in the final product.
