### ISSUE TITLE
Typo under "Important Dates"

### ISSUE THREAD

**Issue by kellyhogan** [joannakl/cs480_s18#42]
On the home page under Important Dates, the phrase should be "Midterm Exam (these dates may change if there are any scheduled changes):"

![image](https://user-images.githubusercontent.com/17225886/36122262-b9613568-1016-11e8-8735-72dfe628cb70.png)

Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by felixplajer** [comment]
"is" should definitely be "if", but I think "schedule" is correct - the exam dates would change if there are changes in the schedule. I don't think it really makes sense to say "scheduled changes" - it's a bit redundant.

**Comment by riosr2** [comment]
I can confirm the issue in Safari Version 9.1.1 (10601.6.17). This can easily be fixed under the index markdown page, https://github.com/joannakl/cs480_s18/blob/gh-pages/index.markdown.

**Comment by dorasun** [comment]
Can I have this issue?

**Comment by joannakl** [comment]
@dorasun  go ahead and work on this issue

**Comment by dorasun** [comment]
@kellyhogan I've left you a note with a link to my fork on pull request #70, please confirm if this fix adequately resolves the issue you saw

**Comment by kellyhogan** [comment]
@dorasun  sorry, I thought I approved this fix already, but it solves the problem. Thanks!
