### ISSUE TITLE
Use of slang in course Home Page

### ISSUE THREAD

**Issue by riosr2** [joannakl/cs480_s18#43]
Under the How to Get Help? section of the course [home page](https://joannakl.github.io/cs480_s18/index.html) the word till is used in the following context:

"Do not wait **till** you start getting failing grades because it might be too late by then."

Should this be changed to until?

**Comment by natalietotonchy** [comment]
I can confirm this issue on Safari version 11.0 (13604.1.38.1.6) This can be fixed in the markdown file here: https://github.com/joannakl/cs480_s18/blob/126086fb0ff1f9dc4c522528ac522d9ae2963641/index.markdown

**Comment by adnanislam** [comment]
I'll claim this issue

**Comment by joannakl** [comment]
I'll veto this one. The course website is not really formal enough to worry about these types of differences. 
https://dictionary.cambridge.org/us/grammar/british-grammar/until
