### ISSUE TITLE
Hyperlink for Webopedia link incorrect

### ISSUE THREAD

**Issue by natalietotonchy** [joannakl/cs480_s18#44]
<img width="567" alt="screen shot 2018-02-13 at 10 25 07 am" src="https://user-images.githubusercontent.com/27150975/36157652-46b46f8e-10a8-11e8-9da2-a1f08294328f.png">

The hyperlink to the Webopedia website includes the word "software" instead of just being the word Webopedia. If this was intentional, it is misleading, and the line should be something along the lines of "Webopedia: software definition, software vs. hardware" with only the word Webopedia underlined. 

This issue was found on Safari version 11.0 (13604.1.38.1.6)

**Comment by cr4zyafrican** [comment]
I can confirm this issue. The software should not be part of the hyperlink

Chrome Version 64.0.3282.140

**Comment by adnanislam** [comment]
Issue can be fixed at https://github.com/joannakl/cs480_s18/blob/gh-pages/index.markdown

**Comment by natalietotonchy** [comment]
I would like to claim this issue

**Comment by oekonomi** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
@oekonomi  you can work on this issue

**Comment by natalietotonchy** [comment]
waiting for commit to be merged, fix should resolve the issue. I verify!
