### ISSUE TITLE
No Tutor Office Hours

### ISSUE THREAD

**Issue by wentaozou1** [joannakl/cs480_s18#45]
![screen shot 2018-02-13 at 7 55 51 pm](https://user-images.githubusercontent.com/10876776/36182509-03061c42-10f8-11e8-8042-5d7662a70015.png)
There is no office hours for tutor under the Office Hours, while under the How To Get Help, it says "See the tutors and/or instructors during the post office hours."

**Comment by nrg294** [comment]
I will claim this issue!

**Comment by joannakl** [comment]
Before anybody is assigned to this issue: what is the proposed fix?

**Comment by jhelfgot1** [comment]
The solution would be to un-comment the properties in the _config.yml for tutor_location and tutor_schedule_link [here](https://github.com/joannakl/cs480_s18/blob/0070c58f1f2026272caafb8578b0d799260741fe/_config.yml#L31) and then also add the corresponding information to the[ index.markdown](https://github.com/joannakl/cs480_s18/blob/126086fb0ff1f9dc4c522528ac522d9ae2963641/index.markdown) file under the course essentials header.

I would like to claim this issue.

**Comment by nrg294** [comment]
That seems like the correct fix to me! I would also like to claim this issue

**Comment by mzguimaraes** [comment]
If the other people claiming this issue have been assigned to other issues already, I'd like to claim it.

**Comment by joannakl** [comment]
@jhelfgot1 you can work on this issue
the information should be that Sachin is the tutor and his hours are going to be Mondays 10am-12pm

**Comment by jhelfgot1** [comment]
Sounds good, thanks Joanna.

**Comment by jhelfgot1** [comment]
@joannakl will the tutor's office hours be located at 406 WWH?

**Comment by joannakl** [comment]
yes
