### ISSUE TITLE
Footer mislabeled Fall 2016 Calendar

### ISSUE THREAD

**Issue by ryanchau** [joannakl/cs480_s18#5]
The link is correct, but it should be labeled Spring 2018 Calendar. 

Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by dorasun** [comment]
Problem seems to be in  _includes/footer.html, line 5 
https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/footer.html#L5

**Comment by zdaisyz** [comment]
I think the link might also be wrong, and should direct to: https://www.nyu.edu/registrar/calendars/university-academic-calendar.html#1184

**Comment by eschadt** [comment]
The link is also incorrect. It links to fall 2017. It should either link to fall 2016 as the hyperlink indicates or to our current semester; spring 2018.

**Comment by ryanchau** [comment]
The link brings you to the correct page, you just have to scroll down. Dazigemm's link is more specific.

**Comment by PhrydRhys** [comment]
I would like to take this issue

**Comment by joannakl** [comment]
@PhrydRhys : go ahead with the fix for this issue
