### ISSUE TITLE
class 5 in daily has a wrong background

### ISSUE THREAD

**Issue by joannakl** [joannakl/cs480_s18#50]
In the daily the class backgrounds alternate between shades of gray. The class 5 should have a light gray background.

**Comment by adnanislam** [comment]
This can be fixed by changing the div class found in the top of the file here https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/05.markdown.

I'd also like to claim this issue.

**Comment by AlvaroLuken** [comment]
Though I am unsure how to directly solve the issue (I know it has to do with editing the contents of https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/05.markdown) I would like to claim this issue and work on it.

**Comment by mzguimaraes** [comment]
I'd like to claim this issue if it's still unassigned.

**Comment by joannakl** [comment]
@AlvaroLuken you can work on this issue
