### ISSUE TITLE
Broken link to version control systems slides

### ISSUE THREAD

**Issue by gabegordon** [joannakl/cs480_s18#6]
The link to the slides for class 5 (Version control systems) directs to nonexistent github page.

Issue produced using: Firefox 59.0b7-1

**Comment by zdaisyz** [comment]
Issue replicated on Chrome. 
Think the link should be: https://joannakl.github.io/cs480_s18/slides/week3/version_control_systems#1

**Comment by zdaisyz** [comment]
I would like to work on this issue

**Comment by joannakl** [comment]
@dazigemm : go ahead with the fix for this issue
