### ISSUE TITLE
Typo in "The Rise of the Open-Source Platform" Link

### ISSUE THREAD

**Issue by jhelfgot1** [joannakl/cs480_s18#63]
On the home page of the website, under the "Why Open Source Matters and Why Should You Care?" header, the link to "The Rise of the Open-Source Platform" article reads "The Rise of Open-Source Platform" rather than "The Rise of **the** Open-Source Platform". ([Link to problem](https://joannakl.github.io/cs480_s18/))

**Comment by jhelfgot1** [comment]
I would also be happy to claim this issue if needed.

**Comment by nrg294** [comment]
I would like to claim this issue

**Comment by JimenezJC** [comment]
If this issue still hasn't been assigned I would like to claim it

**Comment by mzguimaraes** [comment]
I'd like to claim this issue if still unassigned.

**Comment by joannakl** [comment]
@nrg294 go ahead and work on this issue
