### ISSUE TITLE
Class #1 repeated twice; class #2 not shown

### ISSUE THREAD

**Issue by dorasun** [joannakl/cs480_s18#7]
Class 1 is repeated twice on the daily list instead of class 2, perhaps an incorrect link on github? Please see attached screenshot. I'm viewing on the latest version of Chrome.

<img width="960" alt="screen shot 2018-02-08 at 12 32 05 pm" src="https://user-images.githubusercontent.com/10905385/35988343-2a9e3936-0ccc-11e8-8da9-f2f9a2a7a82a.png">

**Comment by jfushada** [comment]
Yes, the daily entry for class 2 is available in the github repo (https://github.com/joannakl/cs480_s18/blob/gh-pages/_includes/daily/02.markdown) but is not present in the daily.html page.

**Comment by melissaelopez** [comment]
I can also confirm this issue. The fix might be in the top section of markdown in [https://github.com/joannakl/cs480_s18/blob/gh-pages/daily.html](https://github.com/joannakl/cs480_s18/blob/gh-pages/daily.html), where day 1 is repeated on lines 4 and 5

**Comment by jfushada** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
@jfushada  go ahead and fix this issue
