### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by ashleytqy** [joannakl/cs480_s18#77]
It would be nice to have a `CONTRIBUTING.md` with instructions on how to submit an issue or make a pull request to this project, e.g. https://github.com/avajs/ava/blob/master/contributing.md

**Comment by mzguimaraes** [comment]
I could work on a first draft on this. May I claim this issue?

**Comment by joannakl** [comment]
@mzguimaraes  that would be nice, go ahead
