### ISSUE TITLE
Open Encyclopedia link broken

### ISSUE THREAD

**Issue by zdaisyz** [joannakl/cs480_s18#8]
The link for open encyclopedia on https://joannakl.github.io/cs480_s18/daily.html  is broken.
Browser: Chrome Version 64.0.3282.140 (64-bit)
![screenshot 12 _li](https://user-images.githubusercontent.com/5962606/35987934-213edc5c-0ccb-11e8-8002-8b5539927f3e.jpg)

**Comment by ryanchau** [comment]
Looks like the correct link should be: https://joannakl.github.io/cs480_s18/slides/week2/open_encyclopedia.html

**Comment by gabegordon** [comment]
The link is broken for me as well.
Using: Firefox 59.0b7

**Comment by ryanchau** [comment]
Claiming this issue.

**Comment by joannakl** [comment]
@rchau0623  go ahead and fix this issue - but the link should not be absolute, it should be relative to the slides directory
