### ISSUE TITLE
Twitter plugin not working on Chrome

### ISSUE THREAD

**Issue by Matthew-Herman** [joannakl/cs480_s18#88]
Im using Mac OS 10.12.6 and Chrome 64.0.3282.140. 

### Opening website in Chrome
<img width="1680" alt="screen shot 2018-02-25 at 6 23 42 pm" src="https://user-images.githubusercontent.com/17124331/36647839-67be6242-1a59-11e8-9c87-a24ca708dde5.png">

### Opening in Safari
<img width="1680" alt="screen shot 2018-02-25 at 6 23 25 pm" src="https://user-images.githubusercontent.com/17124331/36647841-6f632a0a-1a59-11e8-9eca-5e22120599f8.png">

**Comment by ashleytqy** [comment]
Works for me though

> Chrome Version 64.0.3282.167 (Official Build) (64-bit)
> MacOS 10.12.6
---
<img width="1279" alt="screen shot 2018-02-25 at 7 06 08 pm" src="https://user-images.githubusercontent.com/11889765/36648256-f9955b26-1a5e-11e8-9a84-913396c21b07.png">

**Comment by Matthew-Herman** [comment]
After checking the console, I realized it's my adblock on Chrome, so there's no bug in the website here and I'm closing this.
