### ISSUE TITLE
Date mislabeled

### ISSUE THREAD

**Issue by ashley-hu** [joannakl/cs480_s18#9]
Under Class 5, the date is wrong

Browser: Google Chrome
Version: 63.0.3239.132

**Comment by jfushada** [comment]
Yes, it says Tue, 2/66  while it should be Tue, 2/6

**Comment by melissaelopez** [comment]
I can also confirm that this is incorrect. Perhaps the issue can be found at cs480_s18/_includes/daily/05.markdown.

**Comment by ghost** [comment]
I will claim this issue!

**Comment by wentaozou1** [comment]
I also want to claim this issue, but I found other issues with the day, most of the Thursday lectures have been labeled as Tue.

**Comment by joannakl** [comment]
@zadner  go ahead and work on this issue - the resolution should take case of the day errors mentioned in the followup discussion
