### ISSUE TITLE
Broken GitHub link

### ISSUE THREAD

**Issue by ashleytqy** [joannakl/cs480_s18#93]
Link to GitHub currently links to https://github.com/orgs/-ossd-snyu18/

Fix in `_includes/header.html`, on this line –
```
<li><a href="https://github.com/orgs/-ossd-snyu18/" target="_blank">GitHub</a></li>
```

**Comment by dorasun** [comment]
I noticed this too on the latest version of chrome, link should be:
https://github.com/nyu-ossd-s18

**Comment by joannakl** [comment]
Yes, it is a broken link even though it was corrected and verified in #62. It seems that the last commit introduced the problem. 

This link should be handled by site-specific variables  set in _config.yml file instead of being hardcoded in that file. (Similar to how the piazza link is handled).

**Comment by ashley-hu** [comment]
I would like to claim this issue.

**Comment by joannakl** [comment]
@ashley-hu  you can work on this
