### ISSUE TITLE
Daily page open data week section typo

### ISSUE THREAD

**Issue by oekonomi** [joannakl/cs480_s18#94]
Under the open data week section on the daily page, there is a typo in the second bullet point
"in your blog describe the event (optional: post a selfie of yourself at the event, make sure that it is clear that you are at that event, alternative: email a the picture to Joanna)"

It should either say "email a picture" or "email the picture".

Issue noticed on Chrome Version 64.0.3282.186 on Windows.

**Comment by ryanchau** [comment]
This issue is located in: cs480_s18/_includes/daily/NYC_OpenDataWeek.markdown in line 14. 

If possible I would like to claim this issue.

**Comment by joannakl** [comment]
thanks for reporting it

@rchau0623  you can work on it
