### ISSUE TITLE
Typo in History Slides

### ISSUE THREAD

**Issue by ryanchau** [joannakl/cs480_s18#96]
In cs480_s18/slides/week1/history.html on line 38, firure should be figure. 

Issue noticed on Chrome Version 64.0.3282.186 on Ubuntu.

**Comment by rchau0623** [comment]
I would also like to fix this issue if that's alright.

**Comment by extra-mayo** [comment]
Can confirm on Version 64.0.3282.186 (Official Build) (64-bit):  
![alt text](https://i.gyazo.com/764b865b2493400a44a9c888a08576c1.png)

The fix is to fix that spelling located in In cs480_s18/slides/week1/history.html on line 38. 
I would like to claim this issue please!

**Comment by joannakl** [comment]
Thanks for reporting.
@extra-mayo  you can work on it.
