### ISSUE TITLE
Broken link to Danna Kelmer's LinkedIn page

### ISSUE THREAD

**Issue by ghost** [joannakl/cs480_s18#98]
When you click on the [link](https://www.linkedin.com/in/dannakelmer/]) (under Class # 19 Tue, 4/3), you get a "Page not found" redirect. It looks like there's an extra "[" after the "/" in the link, as when you remove it, it takes you to the correct page.

Identified on Firefox Quantum 59.0.1

EDIT: Thought it was necessary to add that, interestingly enough, it seems that when you click the link (copied directly from the course page) in this comment, LinkedIn will correct the mistake and redirect you to the correct page. However, the link on the course website as of this time (Fri Mar 30, 15:27) remains broken.

**Comment by kellyhogan** [comment]
I can confirm this issue with Chrome Version 65.0.3325.162 (Official Build) (64-bit).

I would also like to work on this issue.

**Comment by joannakl** [comment]
Thanks for reporting it.
@kellyhogan  go for it with a fix
